### ISSUE TITLE
How to reference files in E-Mail template

### ISSUE THREAD

**Issue by clck-dr** [ryntab/Directus-Mailer#2]
Hi,
thanks for your solution.
I was wondering how to reference attachment files in E-Mail template written in liquid?
Could you add code or give me a hint?

Best regards
Daniel

**Comment by ryntab** [comment]
Sorry for the late response, if you are asking how to reference the contents of an attachment within a liquid template. It's not possible, and probably won't be.

If you are asking how to add an attachment to a liquid template email you can do that like this...

```JSON
{
  "subject": "You have been invited to join Test.com",
  "to": "user@gmail.com",
  "template": {
    "name": "account-status",
    "data": {
      "url": "www.google.com",
      "title": "You have been invited!"
    }
  },
  "files": [
    "c17d967b-b257-414d-ab92-41ae6d0784ed",
    "b507c26f-1333-4a8a-b8df-9731be74542e"
  ],
  "attachments": [
    {
      "filename": "text1.txt",
      "content": "hello world!"
    }
  ]
}
 ```
 
 If that helps let me know! If you have any additional questions let me know.

**Comment by clck-dr** [comment]
Hej,

thank you for your response!
I figured out how to embed images in HTML template written in liquid. Therefor I combined your streamed attachment with an additional cid field. This cid could be referenced in HTML img tags!

```
async function getAttachment(fileId, assetsService) {
  const res = await assetsService.getAsset(fileId, {});
  const { stream, file } = res;

  const attachment = {
    contentType: file.type,
    filename: file.filename_download,
    content: stream,
    cid: file.id,
  };

  return attachment;
}
```

```
<img src="cid:{{ asset.cid }}>
```

Thnak you for your public repo. It helped me alot!

Best regard
Daniel

**Comment by ryntab** [comment]
That's awesome, thanks Daniel. I'll update the docs with a note of this and make some additional changes.
